---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-kdc-01
    box: ${M_BOX:-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_kdcs
      - primary_kdc
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        m_enable_selinux: ${M_ENABLE_SELINUX:-no}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
