---
# Kerberos commands.
afs_kadmin: "/usr/bin/kadmin"
afs_kdestroy: "/usr/bin/kdestroy"
afs_kinit: "/usr/bin/kinit"

# Other commands.
afs_python: "/usr/bin/python3"
afs_gfind: "/usr/bin/find"

# Platform
afs_robotest_webserver: httpd
afs_selinux: yes
