---
- name: Set default configure options for Linux
  set_fact:
    afs_configure_options:
      enable:
        - debug
        - debug-kernel
        - kernel-module
      disable:
        - optimize
      with:
        - linux-kernel-packaging
