---
- name: Converge
  hosts: all
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
  tasks:
    - name: "Include openafs_robotest"
      import_role:
        name: "openafs_robotest"
