---
- name: Setup
  hosts: all
  tasks:
    - name: Prepare selinux
      become: yes
      selinux:
        policy: targeted
        state: "{{ m_enable_selinux | ternary('enforcing', 'permissive') }}"
      when:
        - m_enable_selinux is defined
        - ansible_selinux is defined
        - ansible_selinux | type_debug == 'dict'
        - ansible_selinux.status == 'enabled'

    - name: Prepare /etc/hosts
      become: yes
      copy:
        backup: yes
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          {% for name in hostvars | sort %}
          {{ hostvars[name].ansible_default_ipv4.address }}    {{ hostvars[name].ansible_hostname }}
          {% endfor %}

- name: Converge
  hosts: all
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
    afs_bdist_dir: "~/.cache/ansible-openafs/binaries/bdist{{ m_transarc | ternary('-transarc', '') }}"
  tasks:
    - import_role:
        name: openafs_krbserver

    - import_role:
        name: openafs_server

    - include_role:
        name: openafs_client
      when: m_with_client | default('no') | bool
