---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance-server
    box: ${BOX-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_cell
      - afs_kdcs
      - afs_databases
      - afs_fileservers
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
