---
- name: Create realm
  hosts: afs_kdcs
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
  tasks:
    - name: Prepare selinux
      become: yes
      selinux:
        policy: targeted
        state: "{{ enable_selinux | ternary('enable', 'permissive') }}"
      when:
        - ansible_selinux is defined
        - ansible_selinux | type_debug == 'dict'
        - ansible_selinux.status == 'enabled'

    - import_role:
        name: openafs_krbserver

- name: Converge
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
  hosts: krbclients
    - name: Prepare selinux
      become: yes
      selinux:
        policy: targeted
        state: "{{ enable_selinux | ternary('enable', 'permissive') }}"
      when:
        - ansible_selinux is defined
        - ansible_selinux | type_debug == 'dict'
        - ansible_selinux.status == 'enabled'

    - import_role:
        name: openafs_krbclient
