---
- name: Converge
  hosts: all
  tasks:
    - import_role:
        name: openafs_common

    - name: Set openafs facts
      become: yes
      openafs_store_facts:
        state: set
        facts:
          test1: this is a test
          test2:
            - item 1
            - item 2
          test3:
            name1: value1
            name2: value2

    - name: Update openafs facts
      become: yes
      openafs_store_facts:
        state: update
        facts:
          test3:
            name3: value3
