---
- name: Setup
  hosts: all
  tasks:
    - name: Prepare selinux
      become: yes
      selinux:
        policy: targeted
        state: "{{ m_enable_selinux | ternary('enforcing', 'permissive') }}"
      when:
        - m_enable_selinux is defined
        - ansible_selinux is defined
        - ansible_selinux | type_debug == 'dict'
        - ansible_selinux.status == 'enabled'

    - name: Prepare /etc/hosts
      become: yes
      copy:
        backup: yes
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          {% for name in hostvars | sort %}
          {{ hostvars[name].ansible_default_ipv4.address }}    {{ hostvars[name].ansible_hostname }}
          {% endfor %}

- name: Realm
  hosts: afs_kdcs
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
  tasks:
    - import_role:
        name: "openafs_krbserver"

    - name: Create AFS service key
      become: yes
      no_log: yes
      openafs_principal:
        state: present
        principal: afs/example.com
        encryption_types:
          - aes128-cts
          - aes256-cts
      register: service_key_results

    - name: Download service keytab
      become: yes
      fetch:
        flat: yes
        src: "{{ service_key_results.keytab }}"
        dest: "{{ afs_local_dir }}/rxkad.keytab"
      register: download_results

    - debug:
        var: download_results

    - name: Download admin keytab
      become: yes
      fetch:
        flat: yes
        src: "/var/lib/ansible-openafs/keytabs/{{ afs_admin_principal | d('admin') }}.keytab"
        dest: "{{ afs_local_dir }}/{{ afs_admin_principal | d('admin') | replace('/', '.') }}.keytab"
      register: download_results

    - debug:
        var: download_results

    - name: Create user principals
      become: yes
      openafs_principal:
        state: present
        principal: "{{ item }}"
      register: principals
      with_items: "{{ afs_users }}"

    - name: Download keytabs
      become: yes
      fetch:
        flat: yes
        src: "{{ item.keytab }}"
        dest: "{{ afs_local_dir }}/keytabs/"
      with_items: "{{ principals.results }}"

- name: Generate csdb.yaml
  hosts: afs_databases
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
    afs_csdb_file: "{{ afs_local_dir }}/csdb.yaml"
  tasks:
    - import_role:
        name: openafs_common
        tasks_from: generate_csdb

- name: Converge
  hosts: all
  vars:
    afs_local_dir: "{{ molecule_ephemeral_directory }}/example.com"
    afs_csdb_file: "{{ afs_local_dir }}/csdb.yaml"
  tasks:
    - import_role:
        name: "openafs_krbclient"
    - import_role:
        name: "openafs_server"
    - import_role:
        name: "openafs_client"
    - import_role:
        name: "openafs_cell"
