---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-cell-01
    box: ${M_BOX:-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_kdcs
      - afs_databases
      - afs_fileservers
      - afs_clients
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        afs_install_method: packages
        afs_module_install_method: kmod
        afs_users:
          - user01
        m_enable_selinux: ${M_ENABLE_SELINUX:-no}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    # - idempotence
    # - lint
    - verify
    - cleanup
    - destroy
