---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance-cell
    box: ${BOX-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_kdcs
      - afs_databases
      - afs_fileservers
      - afs_clients
provisioner:
  name: ansible
verifier:
  name: ansible
  inventory:
    group_vars:
      all:
        enable_selinux: ${ENABLE_SELINUX-yes}
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
