---
- name: Add epel yum repo
  become: yes
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages
  become: yes
  yum:
    name:
      - git
      - python3-pip
    state: present

- name: Install Robot Framework OpenAFS library
  become: yes
  pip:
    name: robotframework-openafslibrary
    state: present
