---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-client-02
    box: ${M_BOX:-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_clients
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    group_vars:
      afs_clients:
        m_update_kernel: ${M_UPDATE_KERNEL:-no}
        m_enable_selinux: ${M_ENABLE_SELINUX:-no}
        m_transarc: ${M_TRANSARC:-no}
        afs_install_method: bdist
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
