---
- name: Gather
  setup:
  when: ansible_distribution is undefined

- name: Install remote server
  vars:
    _path: "{{ role_path }}/tasks/install"
  include_tasks: "{{ afs_remoteserver_item }}"
  loop_control:
    loop_var: afs_remoteserver_item
  with_first_found:
    - "{{ _path }}/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "{{ _path }}/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ _path }}/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "{{ _path }}/{{ ansible_os_family | replace(' ', '_') }}.yaml"
    - "{{ _path }}/{{ ansible_system | replace(' ', '_') }}.yaml"
    - "{{ _paht }}/unknown.yaml"
