---
- name: Find binary distribution archive filenames
  local_action:
    module: find
    path: "{{ afs_bdist_dir }}/{{ afs_bdist_dist }}/{{ afs_bdist_arch }}"
    patterns:
      - "*.tar.gz"
      - "*.tar.bz2"
      - "*.tar.xz"
  register: find_results

- set_fact:
    tarballs: "{{ find_results.files | map(attribute='path') | list | sort(reverse=True, case_sensitive=True) }}"

- name: Verify binary distribution archive was found
  assert:
    that: tarballs | count > 0
    msg: "No binary distribution archives found in controller directory '{{ afs_bdist_dir }}/{{ afs_bdist_dist }}/{{ afs_bdist_arch }}'."

- name: Create upload directory
  file:
    state: directory
    path: /tmp/ansible-openafs/bdist

- name: Upload binary distribution
  unarchive:
    src: "{{ tarballs[0] }}"
    dest: /tmp/ansible-openafs/bdist/
