---
# Keys for Solaris Studio installation
afs_devel_oracle_key: "{{ '~/.certs/pkg.oracle.com.key.pem' | expanduser }}"
afs_devel_oracle_cert: "{{ '~/.certs/pkg.oracle.com.certificate.pem' | expanduser }}"
