---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-server-04
    box: ${M_BOX:-generic/centos7}
    memory: 4096
    cpus: 1
    groups:
      - afs_cell
      - afs_kdcs
      - afs_databases
      - afs_fileservers
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    group_vars:
      all:
        afs_cell: example.com
        afs_service_keytab: ${M_KEYTAB:-../default/files/example-aes.keytab}
        afs_install_method: scm
        m_enable_selinux: ${M_ENABLE_SELINUX:-no}
        m_with_client: ${M_WITH_CLIENT:-no}
        m_gitref: "${M_GITREF:-master}"
        m_gitrepo: "${M_GITREPO-git://git.openafs.org/openafs.git}"
        m_transarc: ${M_TRANSARC-no}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
