---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: m-role-client-01
    box: "${AFS_IMAGE:-generic/centos7}"
    groups:
      - afs_clients
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        afs_cell: "example.com"
        afs_cell_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_csdb_file: ""
        afs_install_method: "source"
        afs_git_repo: "${AFS_GIT_REPO:-git://git.openafs.org/openafs.git}"
        afs_git_version: "${AFS_GIT_VERSION:-master}"
        # afs_configure_options: "--enable-transarc-paths --with-linux-kernel-packaging"
        afs_always_build: "${AFS_ALWAYS_BUILD:-no}"
        afs_clean_build: "${AFS_CLEAN_BUILD:-yes}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
