---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-devel-01
    box: ${M_BOX:-generic/centos7}
    memory: 4096
    cpus: 1
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        m_enable_selinux: ${M_ENABLE_SELINUX:-yes}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
