---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance-devel
    box: ${BOX-generic/centos8}
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
