---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance-devel
    box: ${BOX-generic/centos7}
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        enable_selinux: ${ENABLE_SELINUX-yes}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
