---
- name: Make partition directory
  become: yes
  file:
    path: /vicep{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items: "{{ afs_partitions }}"
  when: afs_partitions is defined

- name: Enable always attach mode for partition
  become: yes
  copy:
    content: ""
    dest: /vicep{{ item }}/AlwaysAttach
    force: no
    owner: root
    group: root
    mode: 0600
  with_items: "{{ afs_partitions }}"
  when: afs_partitions is defined
