---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: m-role-server-01
    box: "${AFS_IMAGE:-generic/centos7}"
    groups:
      - afs_databases
      - afs_fileservers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        afs_cell: "example.com"
        afs_cell_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_install_method: "sdist"
        afs_csdb_file: "${MOLECULE_EPHEMERAL_DIRECTORY}/csdb.yaml"
        afs_pseudo_partitions: ['a', 'b']
        afs_service_keytab: "../__files__/example-aes.keytab"
        afs_install_archive: "${AFS_INSTALL_ARCHIVE}"
        # afs_configure_options: "--enable-transarc-paths"
        afs_always_build: "${AFS_ALWAYS_BUILD:-no}"
        afs_clean_build: "${AFS_CLEAN_BUILD:-yes}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
