---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-devel-02
    box: ${M_BOX:-generic/centos7}
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        m_update_kernel: ${M_UPDATE_KERNEL:-no}
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
