---
#
# Post rsync tasks for CentOS 6.x
#

# Patch up the contexts for the directories and files
# that were created while in unconfined_t
- name: Restore directory contexts for selinux
  become: yes
  command: restorecon -ir /lib/modules

- name: Install module probe script
  become: yes
  copy:
    src: CentOS-6/openafs-client.modules
    dest: /etc/sysconfig/openafs

- name: Update shared library cache
  become: yes
  command: /sbin/ldconfig
  changed_when: false

- name: Update module dependencies
  become: yes
  command: depmod -a
  changed_when: false

- name: Check afs filesystem mount point
  # We can't use the mount module to do this because it only checks
  # /etc/fstab; /afs is never there. Thoe --fake option requires root.
  become: yes
  command: "/usr/bin/mount --fake --verbose {{ afs_mountpoint }}"
  args:
    warn: no
  ignore_errors: yes
  register: mount_result

- name: Make afs filesystem mount point
  become: yes
  file:
    path: "{{ afs_mountpoint }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: mount_result.rc != 0

- name: Make cache directory
  become: yes
  file:
    state: directory
    path: "{{ afs_cachedir }}"
    mode: 0700
    owner: root
    group: root

- name: Install startup options config file
  become: yes
  copy:
    # This file has sections for the client and server.
    # Use force:no to avoid clobbering if already installed by the client.
    src: CentOS-6/openafs.sysconfig"
    dest: /etc/sysconfig/openafs
    force: no

- name: Set client startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client
