---
- name: Ensure public cell configuration file exists (CellServDB.dist)
  become: yes
  copy:
    content: ""
    dest: "{{ afs_viceetcdir }}/CellServDB.dist"
    mode: 0644
    force: no

- name: Check CellServDB file
  delegate_to: localhost
  stat:
    path: "{{ afs_local_dir }}/CellServDB"
  register: cellservdb_st

- name: Update local cell configuration file (CellServDB.local)
  become: yes
  copy:
    src: "{{ afs_local_dir }}/CellServDB"
    dest: "{{ afs_viceetcdir }}/CellServDB.local"
    mode: 0644
    owner: root
    group: root
  when: cellservdb_st.stat.exists is defined and cellservdb_st.stat.exists

- name: Ensure local cell configuration file exists (CellServDB.local)
  become: yes
  copy:
    content: ">{{ afs_cell }}  #Cell name\n"
    dest: "{{ afs_viceetcdir }}/CellServDB.local"
    mode: 0644
    owner: root
    group: root
    force: no

- name: Combine local and public cell database (CellServDB.ansible)
  become: yes
  shell: cat CellServDB.local CellServDB.dist > CellServDB.ansible
  args:
    chdir: "{{ afs_viceetcdir }}"
  changed_when: false

- name: Update CellServDB
  become: yes
  copy:
    remote_src: true
    src: "{{ afs_viceetcdir }}/CellServDB.ansible"
    dest: "{{ afs_viceetcdir }}/CellServDB"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart OpenAFS client

- name: Set local cell name
  become: yes
  copy:
    content: "{{ afs_cell }}"
    dest: "{{ afs_viceetcdir }}/ThisCell"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart OpenAFS client

- name: Update cache configuration
  become: yes
  template:
    src: cacheinfo.j2
    dest: "{{ afs_viceetcdir }}/cacheinfo"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart OpenAFS client
