---
# Verify AFS is mounted.
- name: Get mounts.
  command:
    cmd: mount
  check_mode: no
  changed_when: false
  register: mount_results

- name: Print mounts.
  debug:
    var: mount_results
    verbosity: 1

- name: Verify afs filesystem is mounted.
  assert:
    that: mount_results.stdout is regex(_afs_mount_pattern)
    fail_msg: AFS is not mounted.
    success_msg: AFS is mounted.
