---
- name: "Fedora: Install development packages"
  become: yes
  yum:
    state: present
    name:
      - autoconf
      - automake
      - bison
      - elfutils-devel
      - flex
      - fuse-devel
      - gcc
      - git
      - glibc-devel
      - krb5-devel
      - libtool
      - make
      - ncurses-devel
      - pam-devel
      - perl-devel
      - perl-ExtUtils-Embed
      - redhat-rpm-config
      - rpm-build
      - swig
      - wget
  tags: root

- name: "Fedora: Install extra packages"
  become: yes
  yum:
    state: present
    name: "{{ afs_extra_packages }}"
  tags: root
  when: afs_extra_packages is defined
