---
- name: "RedHat: Enable CodeReady Builder repository"
  become: yes
  vars:
    release: "{{ ansible_distribution_major_version }}"
    arch: "{{ ansible_architecture }}"
  community.general.rhsm_repository:
    state: enabled
    name: "codeready-builder-for-rhel-{{ release }}-{{ arch }}-rpms"
  tags: root

- name: "RedHat: Install EPEL release package"
  become: yes
  vars:
    release: "{{ ansible_distribution_major_version }}"
  ansible.builtin.dnf:
    state: present
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ release }}.noarch.rpm"
    disable_gpg_check: yes
  tags: root

- name: "RedHat: Install development packages"
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - autoconf
      - automake
      - bison
      - elfutils-devel
      - flex
      - fuse-devel
      - gcc
      - git
      - glibc-devel
      - jansson-devel
      - krb5-devel
      - libevent-devel
      - libtool
      - make
      - ncurses-devel
      - openssl-devel
      - pam-devel
      - perl-core
      - perl-devel
      - perl-ExtUtils-Embed
      - redhat-rpm-config
      - rpm-build
      - swig
      - wget
  tags: root
