---
- name: "Ubuntu-20: Install development packages"
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - autoconf
      - automake
      - bison
      - flex
      - gcc
      - git
      - libfuse-dev
      - libgc-dev
      - libkrb5-dev
      - libncurses5-dev
      - libperl-dev
      - libtool
      - make
      - swig
      - wget
  tags: root

- name: "Ubuntu-20: Install extra packages"
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ afs_extra_packages }}"
  tags: root
  when: afs_extra_packages is defined
