---
- name: Add EPEL yum repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install development packages
  yum:
    state: present
    name:
      - autoconf
      - automake
      - bison
      - flex
      - fuse-devel
      - gcc
      - git
      - glibc-devel
      - krb5-devel
      - libtool
      - make
      - ncurses-devel
      - pam-devel
      - perl-devel
      - perl-ExtUtils-Embed
      - redhat-rpm-config
      - rpm-build
      - swig
      - wget

- name: Install kernel devel packages
  yum:
    state: present
    name:
      - kernel-devel
  when: afs_devel_build_client | bool

- name: Install kernel devel packages
  yum:
    state: present
    name:
      - elfutils-devel
  when: afs_devel_build_client | bool and (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "8")

