---
#
# Install the OpenAFS kernel module with DKMS. This install method
# requires a private yum repo populated with OpenAFS rpm packages.
#

- name: Add OpenAFS zypper repo
  become: yes
  zypper_repository:
    name: openafs
    description: OpenAFS zypper repo
    repo: "{{ afs_zypper_repo }}"
    disable_gpg_check: yes

- name: Install OpenAFS client with DKMS
  become: yes
  zypper:
    state: present
    name:
      - openafs
      - openafs-client
      - openafs-devel
      - openafs-kernel-source
      - dkms-openafs

- name: Get dkms status
  command: /usr/sbin/dkms status
  check_mode: no
  changed_when: false
  register: dkms_status

- debug:
    var: dkms_status
    verbosity: 1

- name: Verify openafs dkms status is installed
  assert:
    that:
      dkms_status.stdout is regex('^openafs/.*: installed')

- name: Get installation paths
  become: yes
  openafs_contrib.openafs.openafs_get_install_paths:
    package_manager_type: rpm
  register: install_results

- name: Store installation facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      install_method: "{{ afs_install_method }}"
      client_installed: yes
      client_service_name: openafs-client
      client_options: "{{ install_results.afsd_args | d(omit) }}"
      bins: "{{ install_results.bins }}"
      dirs: "{{ install_results.dirs }}"
      cacheinfo: "{{ install_results.cacheinfo }}"
  when: not ansible_check_mode

- name: Set client startup options
  become: yes
  lineinfile:
    path: "/etc/sysconfig//{{ afs_client_service_name }}"
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client

- name: Set client crypt option.
  become: yes
  vars:
    crypt: "{{ afs_crypt | d('off') }}"
  lineinfile:
    path: "/etc/sysconfig//{{ afs_client_service_name }}"
    regexp: "^CRYPT="
    line: 'CRYPT="{{ crypt }}"'
    state: present
  notify:
    - Restart OpenAFS client
