---
#
# Install OpenAFS from a source distribution tarball.
#

- name: Store install method fact
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      install_method: sdist

- include_tasks: "{{ role_path }}/tasks/common/{{ afs_is_server |
                 ternary('setup-service', 'build-and-install') }}.yaml"
  vars:
    checkout_method: upload_sdist
