---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: m-server-03
    box: ${M_BOX:-generic/centos7}
    memory: 2048
    cpus: 1
    groups:
      - afs_cell
      - afs_kdcs
      - afs_databases
      - afs_fileservers
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    group_vars:
      all:
        m_enable_selinux: ${M_ENABLE_SELINUX:-no}
        m_with_client: ${m_with_client:-no}
        afs_install_method: packages
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
