- name: Check for dest directory
  stat:
    path: "{{ afs_client_build_destdir }}"
  register: destdir_st
  when: not afs_client_build_force|bool

- name: Install devel libs/tools
  import_role:
    name: openafs_devel
    tasks_from: main

- name: Build dest directory from source
  import_role:
    name: openafs_devel
    tasks_from: build
  vars:
    afs_devel_build_server: no
    afs_devel_build_client: yes
    afs_devel_builddir: "{{ afs_client_build_builddir }}"
    afs_devel_destdir: "{{ afs_client_build_destdir }}"
    afs_devel_fetch_method: "{{ afs_client_build_fetch_method }}"
    afs_devel_git_repo: "{{ afs_client_build_git_repo }}"
    afs_devel_git_ref: "{{ afs_client_build_git_ref }}"
  when: afs_client_build_force|bool or not destdir_st.stat.exists

- name: Install dest directory to system
  become: yes
  command: rsync -a -K --info=name --checksum . /
  args:
    chdir: "{{ afs_client_build_destdir }}"
  register: rsync_results
  failed_when: rsync_results.rc != 0
  changed_when:
    - rsync_results.stdout | length > 0

- name: Platform specific post-rsync tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "post-rsync/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "post-rsync/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "post-rsync/{{ ansible_distribution }}.yaml"
    - "post-rsync/{{ ansible_os_family }}.yaml"
    - "unknown.yaml"
  when: rsync_results.changed
