---
- name: Prevent services from starting during install
  become: yes
  copy:
    src: Debian/policy-rc.d
    dest: /usr/sbin/policy-rc.d
    mode: "0755"
    backup: yes
  register: change_policy_rc_result

- name: Install OpenAFS server packages
  become: yes
  apt:
    state: present
    install_recommends: no
    update_cache: yes
    name:
      - openafs-fileserver
      - openafs-dbserver
      - openafs-krb5
  notify:
    - Restart OpenAFS servers

- name: Remove custom policy-rc file
  become: yes
  file:
    path: /usr/sbin/policy-rc.d
    state: absent
  when: change_policy_rc_result.changed

- name: Gather OpenAFS installation facts
  become: yes
  openafs_gather_facts:
    state: update
    pkg: deb
    
- name: Set bosserver startup options
  become: yes
  template:
    src: Debian/openafs-fileserver.j2
    dest: /etc/default/openafs-fileserver
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart OpenAFS servers