---
- name: Prevent services from starting during install
  become: yes
  copy:
    src: "Debian/policy-rc.d"
    dest: "/usr/sbin/policy-rc.d"
    mode: "0755"
    backup: yes
  changed_when: false

- name: Install OpenAFS server packages
  become: yes
  apt:
    state: present
    install_recommends: no
    update_cache: yes
    name:
      - openafs-fileserver
      - openafs-dbserver
      - openafs-krb5
  notify:
    - Restart OpenAFS servers

- name: Save OpenAFS installation facts
  become: yes
  openafs_install_facts:
    state: update
    package_type: deb

- name: Remove custom policy-rc file
  become: yes
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
  changed_when: false

- name: Set bosserver startup options
  become: yes
  template:
    src: "Debian/openafs-fileserver.j2"
    dest: "/etc/default/openafs-fileserver"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart OpenAFS servers
