---
- name: Add OpenAFS yum repo
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_yum_repo }}"
    gpgcheck: no

- name: Install OpenAFS server packages
  become: yes
  yum:
    state: present
    name:
      - openafs-server
      - openafs-krb5

- name: Save OpenAFS installation facts
  become: yes
  openafs_install_facts:
    state: update
    package_type: rpm

- name: Set bosserver startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers
