---
- name: Trace repo url
  debug:
    var: afs_server_repo_url

- name: Add OpenAFS yum repo
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_server_repo_url }}"
    gpgcheck: no

- name: Install OpenAFS server packages
  become: yes
  yum:
    state: present
    name:
      - openafs
      - openafs-server
      - openafs-krb5

- name: Gather OpenAFS installation facts
  become: yes
  openafs_gather_facts:
    state: update
    pkg: rpm
    
- name: Set bosserver startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers