---
- name: Trace repo url
  debug:
    var: afs_server_repo_url

- name: Add OpenAFS yum repo
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_server_repo_url }}"
    gpgcheck: no

- name: Install OpenAFS server packages
  become: yes
  yum:
    state: present
    name:
      - openafs-server
      - openafs-krb5

- name: Set bosserver startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers

- name: Set OpenAFS commands
  set_fact:
    afs_akeyconvert: /usr/sbin/akeyconvert
    afs_asetkey: /usr/sbin/asetkey
    afs_dafileserver: /usr/afs/bin/dafileserver
    afs_dasalvager: /usr/afs/bin/dasalvager
    afs_davolserver: /usr/afs/bin/davolserver
    afs_fileserver: /usr/afs/bin/fileserver
    afs_ptserver: /usr/afs/bin/ptserver
    afs_pts: /usr/bin/pts
    afs_rxdebug: /usr/sbin/rxdebug
    afs_salvager: /usr/afs/bin/salvager
    afs_salvageserver: /usr/afs/bin/salvageserver
    afs_udebug: /usr/bin/udebug
    afs_vlserver: /usr/afs/bin/vlserver
    afs_volserver: /usr/afs/bin/volserver
    afs_vos: /usr/sbin/vos

- name: Set OpenAFS installation paths
  set_fact:
    afs_afsbosconfigdir: /usr/afs/local
    afs_afsconfdir: /usr/afs/etc
    afs_afsdbdir: /usr/afs/db
    afs_afslocaldir: /usr/afs/local
    afs_afslogdir: /usr/afs/logs
    afs_afssrvdir: /usr/afs/bin
    afs_viceetcdir: /usr/vice/etc
