---
#
# Setup the systemd service on clients installed from source.
#

# The afsd options must be saved on the node as local facts
# for use by the openafs_volume module.
# The service name is install method dependent.
- name: Store client facts
  become: yes
  openafs_contrib.openafs.openafs_store_facts:
    state: update
    facts:
      client_options: "{{ afs_afsd_opts }}"
      client_service_name: openafs-client

- name: Install systemd unit file
  become: yes
  template:
    src: openafs-client.service.j2
    dest: "/etc/systemd/system/{{ afs_client_service_name }}.service"
  register: unit_file

- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes
  when: unit_file.changed
