---
- name: Install packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-packages/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "install-packages/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "install-packages/{{ ansible_distribution }}.yaml"
    - "install-packages/{{ ansible_os_family }}.yaml"
    - "unknown.yaml"
