---
- name: Install Setools
  yum:
    name:
      - policycoreutils-python
      - setools-console
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < "8"

- name: Test for presence of openafs module in SELinux
  shell: semodule -lstandard | grep -E '^openafs\s+{{ afs_selinux_openafs_version }}$'
  register: module_result
  changed_when: False
  failed_when: False

- name: Copy the SELinux module for openafs server
  template:
    dest: "/tmp/{{ item }}"
    src: "{{ role_path }}/templates/{{ item }}.j2"
  when: module_result.rc > 0
  with_items:
    - openafs.te
    - openafs.fc

- name: Build SELinux module for openafs server
  command: "{{ item }}"
  args:
    chdir: "/tmp"
  when: module_result.rc > 0
  with_items:
    - "checkmodule -M -m -o openafs.mod openafs.te"
    - "semodule_package -o openafs.pp -m openafs.mod -f openafs.fc"
    - "semodule -i openafs.pp"
