---
# Set the AFS service key. As of OpenAFS 1.8.0, the akeyconvert tool was
# provided to import the keys into the OpenAFS keyfile formats. Versions 1.6.5
# to 1.6.x use the rxkad.keytab directly.  Versions before 1.6.5 are not
# supported here.  We also assume the kadmin tool is new enough to support the
# -norandkey option to distribute the keys.

- name: Copy service key
  become: yes
  copy:
    src:  "{{ afs_local_dir }}/rxkad.keytab.ansible"
    dest: "{{ afs_afsconfdir }}/rxkad.keytab.ansible"
    mode: 0700
    owner: root
    group: root

- name: Check for key value changes
  become: yes
  copy:
    src: "{{ afs_afsconfdir }}/rxkad.keytab.ansible"
    dest: "{{ afs_afsconfdir }}/rxkad.keytab"
    remote_src: yes
  register: keytab
  
- name: Check for akeyconvert availability
  stat:
    path: "{{ afs_asetkey }}"
  register: asetkey
  changed_when: False

- name: Set the service key
  become: yes
  command: "{{ afs_asetkey }} add 1 {{ afs_afsconfdir }}/rxkad.keytab afs/{{ afs_cell }}" 
  when: keytab.changed and asetkey.stat.exists
  notify:
    - Restart OpenAFS servers
