---
- name: Create cell volumes
  hosts: "{{ afs_admin_client | default(groups['afs_clients'][0]) }}"
  vars:
    afs_volumes:
      - name: test
  pre_tasks:
    - name: Connecting
      wait_for_connection:
  roles:
    - openafs_client
    - openafs_cell
  tags:
    - volume
