---
#
# Example play to build and OpenAFS binaries.
#

- name: Build and install OpenAFS from source
  hosts: builders
  roles:
    - openafs_devel
  tasks:
    - name: Checkout source
      git:
        repo: https://github.com/openafs/openafs.git
        dest: ~/src/openafs
        version: master
      register: checkout_results

    - name: Build OpenAFS binary distribution
      openafs_build:
        projectdir: ~/src/openafs
        clean: "{{ checkout_results.changed }}"
        target: dest
        destdir: packaging/dest
        configure_options:
          enable:
            - debug
            - transarc-paths
            - kernel-module
          with:
            - linux-kernel-packaging
          without:
            - swig
      register: build_results

    - name: Build results
      debug:
        var: build_results
        verbosity: 1
