---
#
# Example play to build and install OpenAFS in the legacy
# Transarc installation style.
#
# * builds the server and client binaries in one build step
# * configure options for Transarc paths
# * installs the binaries on the target system after the build completes
# * logs of the build and installation are saved on the remote
#   system in the `$HOME/src/openafs/.ansible` directory.
# * run with -v to show the build and install results during the play
#

- name: Build and install OpenAFS from source
  hosts: "{{ afs_devel | default('afs_cell') }}"
  roles:
    - openafs_devel
  tasks:
    - name: Checkout source
      git:
        repo: https://github.com/openafs/openafs.git
        dest: ~/src/openafs
        version: master
      register: checkout_results

    - name: Build OpenAFS transarc-style distribution
      openafs_build:
        projectdir: ~/src/openafs
        clean: "{{ checkout_results.changed }}"
        target: dest
        destdir: packaging/dest
        state: kmodready
        configure_options:
          enable:
            - debug
            - transarc-paths
            - kernel-module
          with: linux-kernel-packaging
          without: swig
      register: build_results

    - name: Build results
      debug:
        var: build_results
        verbosity: 1

    - name: Install OpenAFS binaries
      become: yes
      openafs_install:
        destdir: "{{ build_results.destdir }}"
        logdir: "{{ build_results.logdir }}"
      register: install_results

    - name: Install results
      debug:
        var: install_results
        verbosity: 1
