---
#
# Deploy kerberos realm.
#
- name: Wait for guests to start
  hosts: afs_cell
  gather_facts: no
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:

- name: Create Kerberos realm
  hosts: afs_kdcs[0]
  become: yes
  any_errors_fatal: true
  roles:
    - openafs_krbserver

- name: Install Kerberos clients
  hosts: afs_cell
  become: yes
  any_errors_fatal: true
  roles:
    - openafs_krbclient
